name: Nix Build
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build (flake)
        run: nix build .#default
      - name: Smoke run
        run: ./result/bin/timerctl now
