name: Release (GoReleaser)

on:
  push:
    tags:
      - "v*.*.*"     # e.g. v0.2.0
      - "v*.*.*-*.*" # e.g. v0.2.0-rc.1

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # important: we need full history for changelog

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Go version
        run: go version

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
